[tool:pytest]
# pytest.ini
[pytest]
markers =
    unit: unit tests 
    functional: functional tests
testpaths = tests
pythonpath = .
addopts = -v --cov --cov-report=html --cov-report=term --tb=short 

